### ISSUE TITLE
[feature-request] Support for S3 prefixes

### ISSUE THREAD

**Issue by jonasfj** [mozilla/sccache#1]
Hi,

I was discussing TC support for sscache with @gregarndt recently, and we found that it would be extremely nice if sscache supported S3 prefixes.

Essentially, instead of giving sscache just a `bucket` we would like to give it `bucket` and a `prefix`.
Such that all keys are stored under the given prefix in the bucket.

In `taskcluster-auth` we have an end-point that given a scope `auth:aws-s3:read-write:<bucket>/<prefix>` will return temporary S3 credentials with read-write access to a specific subfolder/prefix on S3.
We already need a bucket for every region, not having to do separate buckets for try and production, would be nice. Instead we could just use separate prefixes, which we can grant access to using scopes.

Notably, this will make it a lot easier if someone wanted to experiment with sscache and wanted isolated storage to avoid poisoning try or production. As giving such isolated storage would be a matter of issuing a scope, rather than creating a new bucket in every region.

http://docs.taskcluster.net/auth/api-docs/#awsS3Credentials

**Comment by luser** [comment]
Coming back around to this, it sounds like all we would need to do to support this feature would be to provide a way to set the prefix (an `SCCACHE_BUCKET_PREFIX` env var, say) and then for the S3 code to prefix key names with the prefix. Does that sound correct?

So if the bucket is 'my-sccache', instead of `GET http://my-sccache.s3.amazonaws.com/{key}` we would do `GET http://my-sccache.s3.amazonaws.com/{prefix}{key}`, and similarly for `PUT`. Does that sound correct?

**Comment by jonasfj** [comment]
Yeah, exactly... We did already create a bucket for level-1, 2 and 3, so we don't need it. But it would be a nice feature to have, as it would make it very easy to to isolate sscache into as many trust pools as we want..

Perhaps there is even an argument for creating an sscache pool based on compiler version, granted I wouldn't be surprised if you're already embedding that in the hash :)
