### ISSUE TITLE
Trigger an error if rust incremental enabled

### ISSUE THREAD

**Issue by Xuanwo** [mozilla/sccache#1596]
Sccache cannot cache incremental builds, it is better to throw an error if it is not disabled. We can do this before sccache is started.

Ref: https://github.com/risingwavelabs/risingwave/pull/7838

**Comment by Xuanwo** [comment]
@sylvestre Please mark this issue as `help-wanted` and `good-first-issue`.

**Comment by sylvestre** [comment]
thanks

**Comment by Logarithmus** [comment]
@Xuanwo @sylvestre I think adding this hard check was a bad idea. We just updated to the latest version of sccache at our CI, where we use CARGO_INCREMENTAL, because it really cuts compilation time by several minutes, we tested. Everything worked fine on older versions of `sccache`, and now it's broken. So please, either remove this check completely, because it's useless, or make it just print a warning and continue processing as usual, instead of exiting the program.
