### ISSUE TITLE
Switch S3 storage to use standard storage instead of reduced redundancy

### ISSUE THREAD

**Issue by Riebart** [mozilla/sccache#167]
The current default S3 storage class is reduced redundancy (RRS), which offers 99.99% durability, compared to the eleven-nines of durability offered by the other two S3 storage classes. Additionally, in many regions S3 RRS is _more_ expensive than the S3 Standard storage class, and frequently close to twice the cost of the S3 Infrequent Access storage class.

Since this parameter has real effects on the cost to deploy this tool, it should be promoted to a runtime parameter to give users control over the way it is deployed.

There is a separate discussion to have regarding the default value, and whether RRS should be the default storage class.

**Comment by luser** [comment]
Weird! The choice of RRS dates back to the original Python sccache implementation. I would guess that at the time RRS was cheaper and it made since because the storage is reproducible data (since it's just a cache).

It looks like even in us-east RRS is more expensive than standard storage now. Maybe Amazon is deprecating RRS and so never lowered the pricing when it lowered standard storage prices? I did a little Googling and that seems to be the case:
https://mysteriouscode.io/blog/aws-s3-storage-classes-pricing-is-not-what-you-think/ (see the "Update from AWS" bit at the bottom).

We should just switch to using standard storage. Someone could do the math on Infrequent Access and see if it works out cheaper for sccache's usage patterns, but given that it's twice the price per-request I suspect it's not.

cc @glandium

**Comment by luser** [comment]
It's just a matter of removing this line:
https://github.com/mozilla/sccache/blob/6267caf603d5a06e8a4b9391ffa02f6125e5ba9b/src/simples3/s3.rs#L126

**Comment by Riebart** [comment]
Yeah, the change is a simple one, and it's possible that for large teams using sccache for multiple projects, the at-rest storage costs may outpace the fetch costs, but it really would require some number-crunching to sort that out.

It is unlikely that AWS will actually deprecate RRS in that RRS objects will disappear, but rather do as they have done with EC2 Classic, and remove RRS as an option for new accounts or accounts that are not currently using RRS. Another alternative is to take the SimpleDB route, and simply (hah) remove it from most of their documentation/references, but still provide the service if you know where to look.

Regardless, thanks for responding! :)

**Comment by luser** [comment]
Thanks for pointing this out!
