### ISSUE TITLE
Tag a release so up-to-date sccache binaries are available

### ISSUE THREAD

**Issue by aneeshusa** [mozilla/sccache#209]
We need to get some updated sccache binaries for the Servo CI (we're currently using some older binaries from the rust-lang-ci bucket). It looks like automatic binary release building landed as part of #181, but there hasn't been a release since then to exercise that functionality.

@luser Would it be possible to tag a new release so that versioned static binaries are available for us? We would like to avoid compiling our own binaries for now.

**Comment by luser** [comment]
Ugh, I tagged a new release, but it didn't generate binaries because apparently I don't have a proper token configured in .travis.yml. :-/ I can't figure out if there's a way to do this without generating a token that has write access to all repos in the mozilla organization, which I'm not wild about doing.

**Comment by luser** [comment]
OK, after some discussion I figured out the most sensible way to do this: I created a new GitHub user for this purpose (@sccachereleasebot), added it as a collaborator to this repo, generated a GH token for it, and added that to the .travis.yml. I'll tag another release and hope this works!

**Comment by luser** [comment]
This looks like it worked:
https://github.com/mozilla/sccache/releases/tag/0.2.4

Still waiting on a Travis mac build, but the Linux build is there.

**Comment by luser** [comment]
Yay, the Mac release build finished and is attached to the release!
