### ISSUE TITLE
Add prebuilt binaries of sccache for windows to releases

### ISSUE THREAD

**Issue by Dushistov** [mozilla/sccache#220]
It would be nice to able to download sccache in appveyor scripts.
I found one here: https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror/2017-05-12-sccache-x86_64-pc-windows-msvc , but it would  be great to get recent one from  here: https://github.com/mozilla/sccache/releases

**Comment by luser** [comment]
Thanks for filing an issue! @alexcrichton actually put support for this in our appveyor CI config:
https://github.com/mozilla/sccache/blob/d2c7f925adf0b105a9b87200129d57cf39439ada/appveyor.yml#L41

...but it hasn't been working. I looked into it a bit and I think the problem is due to how I tag + push releases with `cargo-release`. `cargo-release` generates annotated tags (`git tag -a`), and also does another commit on `master` after tagging to bump the version in Cargo.toml, and then pushes both the tag + the new head of `master` all at once. appveyor doesn't trigger a release build in this situation, because it only gets one `push` webhook event, and it just sees it as pushing to `master`:
https://help.appveyor.com/discussions/questions/2133-deploy-setting-for-nuget#comment_39280964

**Comment by luser** [comment]
I opened an issue on `cargo-release` about this: https://github.com/sunng87/cargo-release/issues/43

**Comment by luser** [comment]
I finally got this working, and the 0.2.6 release does include a Windows binary: https://github.com/mozilla/sccache/releases/tag/0.2.6
