### ISSUE TITLE
Failures when used on Windows

### ISSUE THREAD

**Issue by timdaman** [mozilla/sccache#242]
First, thank you for such a helpful utility. It has really speed up a lot of workloads for me. 

On some of our builds we are getting compile failures that looks like this 

```
sccache: encountered fatal error
	sccache: error : failed to store `xxxx.cc.obj` to cache
	sccache:  cause: failed to store `xxxx.cc.obj` to cache
	sccache:  cause: failed to zip up compiler outputs
	sccache:  cause: The process cannot access the file because it is being used by another process. (os error 32)
```

Our set up is this.

- Sccache version: 0.2.5 and 0.2.6
- Languages: C & C++
- OS: Windows Server 2016
- Hosting: AWS EC2
- Compiler: MSVC 19.0.24210.0 / Visual Studio version: vc14
- Build runner: Cmake
- Antivirus: Realtime scanner disabled
- File Indexing: Disabled

The failure is quite reproducible, it fails on that same command every-time. The compilation is multi-threaded but it looks like it doesn't hit C compilations but C++ ones all fail.

**Comment by timdaman** [comment]
I think this issue may be related to a Windows filesystem quirk. When closing a file it does not immediately become available. Other processes (AV, file indexers, etc) can watch that close and will open the file thus 'locking' it. I have gone through pains to ensure as many of these processes are not running but I think Windows is still doing more. 

I am not a rust coder so please pardon my errors. I edit compiler.rs and changed

    let mut f = File::open(&path)?;

to

   
    let retries = 2;
    let mut f = match
        (0..retries-1).filter_map(|i| {
            if i != 0 { thread::sleep(Duration::from_millis(1000))}
            File::open(&path).ok() }
        ).next()
        {
            Some(file) => file,
            None => File::open(&path)?
        };

which changed the issue. Now I am also seeing errors on the following line

     tmp.persist(path)?;

that look like

     sccache: encountered fatal error
     sccache: error : failed to store `YYYYY.cpp.obj` to cache
     sccache:  cause: failed to store `YYYYY.cpp.obj` to cache
     sccache:  cause: failed to zip up compiler outputs
     sccache:  cause: The process cannot access the file because it is being used by another process. (os error 32)

**Comment by hcs64** [comment]
I keep hitting this while trying to build Firefox with sccache on Windows.
I added a line to dump the path being opened, interestingly it always seems to be a PDB. I noticed the following comment [in mozilla-central](https://searchfox.org/mozilla-central/rev/2466b82b729765fb0a3ab62f812c1a96a7362478/config/rules.mk#131-140):

    # Unless we're building SIMPLE_PROGRAMS, all C++ files share a PDB file per
    # directory. For parallel builds, this PDB file is shared and locked by
    # MSPDBSRV.EXE, starting with MSVC8 SP1. If you're using MSVC 7.1 or MSVC8
    # without SP1, don't do parallel builds.

This suggests that MSPDBSRV.EXE is holding the lock for a common PDB for the whole directory (in this case "generated.pdb"), due to the -FS switch given to cl.

Not sure if this is your problem as well, when building Firefox it is fixed by [these mozconfig options](https://searchfox.org/mozilla-central/rev/2466b82b729765fb0a3ab62f812c1a96a7362478/build/mozconfig.cache#89-91), to embed the debug info in the OBJ files directly.

**Comment by luser** [comment]
Yes, we don't use `-Zi` when building Firefox with sccache on Windows, we use `-Z7` since that puts the debug info directly into the .obj file. It's effectively impossible to cache PDB files that MSVC outputs since they can be shared among object files. We should probably mention this in the documentation somewhere.

Note that `clang-cl` will work reliably (with sccache master) because it does not support `-Zi` (it's just treated as an alias for `-Z7`).

**Comment by Be-ing** [comment]
@luser
> We should probably mention this in the documentation somewhere.

Done: #963
