### ISSUE TITLE
S3: handle 307 Temporary Redirect

### ISSUE THREAD

**Issue by jesskfullwood** [mozilla/sccache#265]
At the moment when I try to hit my S3 bucket at `http://my-bucket.s3.amazonaws.com`, I am getting a redirect
```
HTTP/1.1 307 Temporary Redirect
Location: http://my-bucket.s3.eu-west-2.amazonaws.com/
```
Apparently this [happens sometimes](https://serverfault.com/questions/730958/error-response-was-307-temporary-redirect-when-trying-to-upload-to-buck)

`sccache` doesn't seem to handle this at all, the debug log just says
```
WARN:sccache::cache::s3: Got AWS error: Error(BadHTTPStatus(TemporaryRedirect), State { next_error: None })
```
It would be nice if this was handled more gracefully - ideally transparently following the redirect, or else giving me a way to specify my region in the `SCCACHE_BUCKET` env var.

**Comment by luser** [comment]
Oh, that's unfortunate!

We'd need to [explicitly handle redirects here](https://github.com/mozilla/sccache/blob/df13487fad5874f144ce1316c999170ac3803237/src/simples3/s3.rs#L88) since hyper (the HTTP crate we're using) is pretty low-level. I think that might not be too hard to implement.

We do already support an [`SCCACHE_REGION`](https://github.com/mozilla/sccache/blob/df13487fad5874f144ce1316c999170ac3803237/src/config.rs#L204) environment variable, it's just not mentioned in the docs (oops).
