### ISSUE TITLE
Add expiration on redis keys

### ISSUE THREAD

**Issue by kfir-drivenets** [mozilla/sccache#275]
Currently when using redis as the backing storage for sccache values won't be deleted.
Every key that is added to redis will just stay there for good, even if it is not longer relevant.
Redis offers the expires command (https://redis.io/commands/expire). By using this mechanism one can make sure that the cache server doesn't keep stuff forever.

In our current setup we added a cronjob that scans redis for keys with TTL=-1 (i.e no expiration) and sets expiration on them. A better solution would be that sccache sets the expiration of cache keys upon usage.

**Comment by luser** [comment]
That makes sense. [In the S3 storage backend](https://github.com/mozilla/sccache/blob/5116315a765378004b4611f600d84998cdd60443/src/simples3/s3.rs#L138) we set the expiration date at two weeks. CCing @flxo who implemented the Redis backend.

**Comment by flxo** [comment]
Sounds reasonable. Just a remark: Keys flagged with the EXPIRE command will expire unless modified. Means that accessing a key (cache hit) will *not* renew the TTL. In case you set the expiration to two weeks you would have a cold cache after that period. With this behaviour, setting the expiration time only makes sense if the Redis instances is shared with other things than `sccache` or the memory is not limited.

Our setup looks like the following: We have a dedicated Redis for `sccache` running locally on a ESXi. The Redis is configured to use a maximum amount of memory of a couple of GB (slightly less below the machines RAM) with the `maxmemory` config. Next the eviction policy is set to `allkeys-lru`. From [here](https://redis.io/topics/lru-cache):

`allkeys-lru: evict keys by trying to remove the less recently used (LRU) keys first, in order to make space for the new data added.` 

I think this is approach is prefect match for the `sccache` use case. The Redis memory size may need to fit your projects (size) and user count. In our setup the full cache is filled within 10days. A full CI run uses about 10% and only very few colleagues here use the Redis backend.

I'd vote for using EXPIRE only as a opt in and not as default because of the not renewed TTL on a hit.

**Comment by kfir-drivenets** [comment]
@flxo that sounds like a good way to handle this.
I would suggest adding the suggested redis configuration to the main README as other people will be able to know how to use it.

Now regarding the suggestion on expiration I agree that it cab be opt-in. You can use environment variable to enable it like other configurations for sccache. Regarding the expiration update, you can always issue a new expire command after reading a key from redis (you can use the redis pipeline mode for get + expire command to avoid a performance penalty. You can read about it here https://github.com/redis/hiredis)

**Comment by luser** [comment]
I don't really know anything about configuring or using Redis, so I'm happy to defer to @flxo here. If you think adding better docs for the Redis backend is sufficient, or if some code changes are warranted, either way is fine with me.

**Comment by flxo** [comment]
Ok. I can prepare a note about the Reds LRU feature.

**Comment by flxo** [comment]
@kfir-drivenets I open a micro PR with the documentation enhancement. Is the mentioned approach sufficient for you?

I personally would like to skip the `EXPIRE` feature because it would include another env variable (there are  already many) or another hard to declare default.

**Comment by kfir-drivenets** [comment]
@flxo yep.
Might be worth to consider issuing a warning or something on this matter. On our deployment we only noticed it when the redis server memory footprint got really large.
But from my end, this is good enough.

**Comment by luser** [comment]
> I personally would like to skip the EXPIRE feature because it would include another env variable (there are already many) or another hard to declare default.

We landed support for a config file recently, so things like this should be easier to do now.
