### ISSUE TITLE
Support AWS signature version 4 on S3

### ISSUE THREAD

**Issue by Marwes** [mozilla/sccache#281]
The version 2(?) signature that is currently used is deprecated and does not work on newer regions such as frankfurt. It might be worthwhile to modify the s3 implementation to use https://github.com/rusoto/rusoto instead of the custom one (which I assume supports the new signature).

https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html

**Comment by luser** [comment]
I originally used rusoto for the s3 backend but switched off of it because rusoto didn't support something I needed to do. It has been a few years now so it's likely that things have changed to the point where that's no longer true. However, sccache uses hyper to do asynchronous HTTP requests currently, and given the unstable state of futures/async in the Rust ecosystem I don't know if switching would be straightforward.

If you or someone else would like to look into that I'd be happy to advise or look at patches. It might be the case that waiting for futures to stabilize in the Rust standard library and the crates ecosystem to settle around them is the best path forward.

**Comment by luser** [comment]
An alternate option here would be to simply copy the rusoto v4 signature code into the sccache codebase. We did that with the authentication code originally (although it has since been heavily modified).

**Comment by Marwes** [comment]
I will probably not implement this as just changing the s3 region of the bucket is an easy workaround. Still wanted it documented in case someone else gets bit by it!

**Comment by zaidenwerg** [comment]
> The version 2(?) signature that is currently used is deprecated and does not work on newer regions such as frankfurt. It might be worthwhile to modify the s3 implementation to use https://github.com/rusoto/rusoto instead of the custom one (which I assume supports the new signature).
> 
> https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html

Hey, starting April 2020 new S3 buckets will not support SigV2 anymore. Maybe it's time to reconsider working on this ? 

https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/

**Comment by andrewwebber** [comment]
Is anyone using SCCACHE outside of the US?
In Europe I would probably not want to have network hops over the Atlantic just to use caching on a CI server in Europe?

**Comment by Xuanwo** [comment]
We have implemented this. @sylvestre Please close this issue.
