### ISSUE TITLE
Build failure on Windows due to ring v0.12.1

### ISSUE THREAD

**Issue by buttercookie42** [mozilla/sccache#292]
I'm on Windows 7 and I have both Visual Studio 2015 and 2017 installed, as well as the 2015 Build Tools from the latter.
When trying to install sccache (currently v0.2.7), building fails because the build for ring v0.12.1 errors out.

It seems that this might be due to briansmith/ring#648, in which case upgrading to ring v0.13 would fix this. I've got no idea though which dependency exactly is pulling in the problematic version of ring.

**Comment by luser** [comment]
We're using ring 0.13.2 on master now since https://github.com/mozilla/sccache/pull/273 . I'm not quite ready to make a new release yet since we're still merging large changes for the distributed compilation feature, but the code on master ought to work fine (distributed compilation is behind a cargo feature).
