### ISSUE TITLE
Docs should mention s3 bucket setup instructions

### ISSUE THREAD

**Issue by petemill** [mozilla/sccache#343]
In order for an s3 bucket to be compatible with sccache, there are specific requirements:
- all objects inside the bucket should be publicly accessible via a custom bucket policy
- users must have specific object put permissions

**Comment by luser** [comment]
We've got https://github.com/mozilla/sccache/pull/337 on adding auth to S3 GET so that you could use a bucket without public access but otherwise this sounds correct. It has been a while since I created a bucket (even for testing) so I'm not sure I remember everything. If you've successfully done this recently and would like to write this down (or submit a PR) that would be great!

**Comment by jeromegn** [comment]
What kind of custom policy on the bucket is required?

**Comment by Xuanwo** [comment]
Already added in https://github.com/mozilla/sccache/blob/main/docs/S3.md. You are welcome to submit new topics to improve our documents.
