### ISSUE TITLE
unconditionally rebuilds all deps on rust nightly

### ISSUE THREAD

**Issue by matthiaskrgr** [mozilla/sccache#436]
calling `cargo build ; cargo build` will cause sccache to try to rebuild the entire dep tree + root crate twice, even though nothing changed and it should technically not.

````
cargo clean ; cargo build ; cargo build
   Compiling serde v1.0.80
   Compiling ryu v0.2.7
   Compiling itoa v0.4.3
   Compiling serde_json v1.0.39 (/home/matthias/vcs/github/serde_json)
    Finished dev [unoptimized + debuginfo] target(s) in 3.75s
   Compiling itoa v0.4.3
   Compiling ryu v0.2.7
   Compiling serde v1.0.80
   Compiling serde_json v1.0.39 (/home/matthias/vcs/github/serde_json)
    Finished dev [unoptimized + debuginfo] target(s) in 1.16s
````

Cargo with rustc (and no RUSTC_WRAPPER) gets this right and does not rebuild anything on the second "cargo build" run.

This happens since this commit in the cargo repo: https://github.com/rust-lang/cargo/commit/6b28a0c0505f19a574a44bffdeccbc07a2d25980

Related cargo ticket: https://github.com/rust-lang/cargo/issues/6976

**Comment by luser** [comment]
I tried this out on my simple [snippet](https://github.com/luser/snippet) crate and assuming I set `CARGO_INCREMENTAL=0` so that sccache will cache the top-level crate I can reproduce it. I think the issue here is that sccache isn't caching the rmeta files. However, the cause of that seems to be that rustc is not listing the rmeta in its `--print=file-names` output. I ran `cargo +nightly build -v` on that snippet crate to get the compiler invocations, and added `--print=file-names` [like sccache does internally](https://github.com/mozilla/sccache/blob/ce983d5d1b8d35c71e6b99a6a9b17ed17a6dad1a/src/compiler/rust.rs#L300-L322) and it only shows the rlib:

```
$ rustc +nightly --crate-name itoa /home/luser/.cargo/registry/src/github.com-1ecc6299db9ec823/itoa-0.3.4/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=9de9e07ff885e8a5 -C extra-filename=-9de9e07ff885e8a5 --out-dir /build/snippet/target/debug/deps -L dependency=/build/snippet/target/debug/deps --cap-lints allow --print=file-names
libitoa-9de9e07ff885e8a5.rlib
```

I noted that there's [an existing workaround](https://github.com/mozilla/sccache/blob/ce983d5d1b8d35c71e6b99a6a9b17ed17a6dad1a/src/compiler/rust.rs#L134-L136) in sccache that points to https://github.com/rust-lang/rust/issues/54852 where `rustc --emit=metadata --print=file-names` prints the rlib name and not the rmeta, perhaps this is related?
