### ISSUE TITLE
Move packages for remote caching out of the default feature flag?

### ISSUE THREAD

**Issue by apiraino** [mozilla/sccache#480]
related to pr #461 and #223 (maybe others)

For users that only take advantage of local caching, would it make sense to avoid compiling in packages such as:
- future*
- reqwest
- tokio*
- hyper*
- jsonwebtoken
- openssl
- memcached
- redis
- ... others?

(not sure 100%, though, because I don't know the internals of sccache)

thanks!

**Comment by luser** [comment]
sccache uses a client-server architecture internally so even without any remote storage backends enabled you're still going to wind up building future and tokio. Honestly, I think the annoyance of having to recompile because you forgot to enable storage backend you want is not worth it. We publish binaries for every release so it's fairly easy to use sccache without having to build it.

**Comment by apiraino** [comment]
I see, thanks for explaining. I usually get sccache using Cargo, therefore compiling. But you're right that the releases available are handy.

**Comment by apiraino** [comment]
Just adding a quick note to the discussion.

I'm trying to integrate sccache in CircleCI and TravisCI builds. Consider the use case of using `sccache` in these environments. It's somehow easier to simply run `cargo install sccache` rather than adding the if/then/else logic to download and unpack the right binary for the right architecture (a CI can run on multiple arch).

CI machines are generally slow: the advantage to use `sccache` might be nullified by the time needed to build sccache itself.
