### ISSUE TITLE
Correct dist-toolchain cache invalidation

### ISSUE THREAD

**Issue by chmanchester** [mozilla/sccache#554]
A user reported needing to delete the `dist-client` cache directory locally when moving between rust toolchain versions to correct a version mismatch between local and the distributed builder. We should determine the circumstances where this might happen and correct it.

**Comment by luser** [comment]
The dist client has this concept of "weak toolchain hashes" which are an easy-to-compute hash of some parts of the toolchain:
https://github.com/mozilla/sccache/blob/d3093392af6f593361c229deb36dd14c964c0778/src/dist/cache.rs#L47-L55

It uses those to lookup whether it has already packaged a toolchain, and during packaging it generates a stronger hash from all the files in the toolchain archive, which is what it uses to talk about toolchains with the build server.

For the Rust compiler the weak hash is actually pretty good, it includes the `compiler_shlibs_digests` that get calculated when sccache finds a Rust compiler (the hashes of all the shared libraries in `$(rustc --print=sysroot)/lib`, or `/bin` on Windows):
https://github.com/mozilla/sccache/blob/6371211b151c2d889864169d3f842d04b8a6f0d9/src/compiler/rust.rs#L1003-L1011

The weak map gets persisted as `~/.cache/sccache-dist-client/client/weak_map.json` on Linux so it should be possible to have someone send you that file if they hit this again.

It's also possible that this is related to https://github.com/mozilla/sccache/issues/87--sccache will not do the right thing if someone uses rustup to point the same `rustc` binary at a different actual version of `rustc` during the lifetime of a server process, since the server caches compiler info purely based on path + mtime:
https://github.com/mozilla/sccache/blob/d3093392af6f593361c229deb36dd14c964c0778/src/server.rs#L839

**Comment by chmanchester** [comment]
This seems like #87

**Comment by chmanchester** [comment]
On further inspection, there's the override case to handle, but also the simpler case of a binary path like `.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc` getting an update that we fail to detect. Re-opening this issue to handle the latter.

**Comment by luser** [comment]
That seems like it ought to be handled properly? The sccache server caches compiler info by path + mtime, so if a compiler gets updated that ought to invalidate the cache.
