### ISSUE TITLE
new release of lru-disk-cache with updated dependicies on crates.io ?

### ISSUE THREAD

**Issue by Dushistov** [mozilla/sccache#813]

**Comment by Bobo1239** [comment]
Note that Rust 1.48 will break the current lru-disk-cache release since linked-hash-map 0.2 doesn't contain https://github.com/contain-rs/linked-hash-map/pull/100 which causes a panic (since there's UB) since https://github.com/rust-lang/rust/pull/71274. (e.g. ``panicked at 'attempted to leave type `linked_hash_map::Node<std::ffi::OsString, u64>` uninitialized, which is invalid'``)

**Comment by fasterthanlime** [comment]
> which causes a panic (since there's UB)

We're also seeing this, releasing a new version of `lru-disk-cache` sounds good (or having the older `linked-hash-map` version yanked, see https://github.com/contain-rs/linked-hash-map/pull/100#issuecomment-663302402)

**Comment by glandium** [comment]
lru-disk-cache 0.4.1 now published: https://crates.io/crates/lru-disk-cache/0.4.1

**Comment by fasterthanlime** [comment]
Thanks so much @glandium !
