### ISSUE TITLE
"Average cache read miss" looks very slow.

### ISSUE THREAD

**Issue by boriay** [mozilla/sccache#871]
I have never tried sccache before. A couple of days ago tried it on Windows on big project and today on small project on Linux and experienced the same thing.
It is strange to see `Average cache read miss` with a huge number when cache is empty. Maybe it count compilation time but it's not obvious and compilation time is not interesting in such context imho.

```
sccache --version
sccache 0.2.13
```

```
sccache -s
Compile requests                     40
Compile requests executed            40
Cache hits                            0
Cache misses                         34
Cache misses (C/C++)                 34
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                   0
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.001 s
Average cache read miss           **7.660 s**
Average cache read hit            0.000 s
Failed distributed compilations       0
Cache location                  Local disk: "/home/boriay/.cache/sccache"
Cache size                           19 MiB
Max cache size                       10 GiB
```

**Comment by froydnj** [comment]
It does indeed count compilation time.  I don't think leaving out compilation time would be a good idea: taking your example and modifying it so that compilation time is cut out, what one would wind up with is something like:

```
sccache -s
Compile requests                     40
Compile requests executed            40
Cache hits                            0
Cache misses                         34
Cache misses (C/C++)                 34
...
Average cache write               0.001 s
Average cache read miss           **0.000 s**
...
```

and then you wonder why `sccache` is making your build take so long if cache reads and cache writes are taking the same amount of time.

Likewise for the cache read hit time: that measurement includes the time to preprocess, hash, etc.  I don't think you want to make that strictly about "how long did it take me to contact the cache and receive a response".  You could, perhaps, have separate metrics tracking that for misses and hits (since I think the write time is basically tracking that metric already), but that would be a different issue.

**Comment by boriay** [comment]
What about time on huge cache? May be it is better to change title somehow.
```
Average cache write               0.001 s
Average cache read miss           7.660 s
Average cache read hit            0.000 s
```
