### ISSUE TITLE
NFS (AWS EFS) mount for shared cache using the Local Mount (default) option

### ISSUE THREAD

**Issue by gvasquez95** [mozilla/sccache#944]
Today I configured a setup from AWS ECS Fargate to an EFS mount for shared `sccache`, used for Rust compilations (`rustc`), it works smoothly, although seems not many crates are being cached.

Any possible drawbacks to using this setup? Cache misuse or corruption?

I preferred it to S3, due to the ease of just mounting the EFS to the container.

Comments are welcome!

**Comment by luser** [comment]
> Any possible drawbacks to using this setup? Cache misuse or corruption?

The sccache disk cache is not at all written with this use case in mind, so it just won't work properly. The LRU data for eviction is stored in memory, populated on startup by recursively traversing the cache directory. I don't think you risk corruption, because I *believe* the cache data is written to a temp file and then renamed to the real filename atomically, but it's been a while since I looked at it. If you have concurrent access you'll just have different clients evicting files at different times and getting confused.

If you need a shared cache you'd be better served using something like redis or memcached.
