### ISSUE TITLE
[Rust] How to pre-fetch crates ahead of time with sccache?

### ISSUE THREAD

**Issue by kirawi** [mozilla/sccache#989]
Sorry if this has been answered somewhere else already, but I couldn't find a related issue in the time I looked. But is it possible to download crates ahead of time, almost like [cargo-prefetch](https://crates.io/crates/cargo-prefetch)? And a side question, what is the difference between using sccache versus Cargo's cache?

**Comment by luser** [comment]
It's not, because the hash keys are derived from the inputs to the Rust compiler, which include the compiled rlib files of crates that a compile depends on. sccache is a compiler cache, similar in function to ccache. Inasmuch as cargo caches any outputs of compilation it's only because the output directory sticks around between running builds.
